// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ReceptionLogistique.Infrastructure.Persistence;

#nullable disable

namespace ReceptionLogistique.Infrastructure.Migrations
{
    [DbContext(typeof(ReceptionLogistiqueDbContext))]
    partial class ReceptionLogistiqueDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ReceptionLogistique.Domain.Entities.Carton", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PalletId")
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("PalletId");

                    b.ToTable("Cartons", (string)null);
                });

            modelBuilder.Entity("ReceptionLogistique.Domain.Entities.Delivery", b =>
                {
                    b.Property<string>("OrderId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("OrderId");

                    b.ToTable("Deliveries", (string)null);
                });

            modelBuilder.Entity("ReceptionLogistique.Domain.Entities.Pallet", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("DeliveryOrderId")
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("DeliveryOrderId");

                    b.ToTable("Pallets", (string)null);
                });

            modelBuilder.Entity("ReceptionLogistique.Domain.Entities.Product", b =>
                {
                    b.Property<string>("Ref")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CartonId")
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("ExpectedQuantity")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("ReceivedQuantity")
                        .HasColumnType("integer");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Ref");

                    b.HasIndex("CartonId");

                    b.ToTable("Products", (string)null);
                });

            modelBuilder.Entity("ReceptionLogistique.Domain.Entities.Carton", b =>
                {
                    b.HasOne("ReceptionLogistique.Domain.Entities.Pallet", null)
                        .WithMany("Cartons")
                        .HasForeignKey("PalletId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ReceptionLogistique.Domain.Entities.Pallet", b =>
                {
                    b.HasOne("ReceptionLogistique.Domain.Entities.Delivery", null)
                        .WithMany("Pallets")
                        .HasForeignKey("DeliveryOrderId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ReceptionLogistique.Domain.Entities.Product", b =>
                {
                    b.HasOne("ReceptionLogistique.Domain.Entities.Carton", null)
                        .WithMany("Products")
                        .HasForeignKey("CartonId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ReceptionLogistique.Domain.Entities.Carton", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("ReceptionLogistique.Domain.Entities.Delivery", b =>
                {
                    b.Navigation("Pallets");
                });

            modelBuilder.Entity("ReceptionLogistique.Domain.Entities.Pallet", b =>
                {
                    b.Navigation("Cartons");
                });
#pragma warning restore 612, 618
        }
    }
}
